### ISSUE TITLE
Adding any opds source causes SocketException on Android App

### ISSUE THREAD

**Issue by mokjpn** [isaaclyman/bookoscope#5]
**Description**

For Android app version 1.4.0,

When I try to add OPDS URL in Sources, any URL fails.
Error is SocketException:Failed to host lookup:　'http://aozora.textlive.net/catalog.opds'
(OS Error:No address associated with hostname, errorno=7)

The internet connection is well working in any other app.
Same OPDS URL works with iOS version of bookoscope.
Because any URL fails with this error, I suspect it is caused by lacking Internet pernission in the AndroidManifesr.xml file.

**Feed**
http://aozora.textlive.net/catalog.opds

**Comment by isaaclyman** [comment]
Thanks for the report. I'll look into it.

**Comment by isaaclyman** [comment]
I've updated the manifest permissions and submitted a new version to Google Play. Though I don't have a physical Android phone to test with, I tested in an emulator and didn't experience any issues.

It may take a few days to get through Google review. Since this is an open-source project, please feel free to download and build from source if you want the update sooner.

Please let me know if that didn't work, of course, and I'll re-open the issue.
